### ISSUE TITLE
Refactor out code to get the inits, trs, safes, and axioms from a module

### ISSUE THREAD

**Issue by Alex-Fischman** [vmware-research/temporal-verifier#102]
Currently, there are at least five different places in the code where this is done (all three bounded model checkers, verify/module.rs, and inference/basics.rs), and they're all done slightly differently. There should be a single function on Modules that can be called to get this information.

Additionally, this function can be smarter than the current implementations are, by (for example) recursing into Ands.

**Comment by wilcoxjay** [comment]
Thanks for filing this issue! Just to make things a little more concrete, here are the places where we are doing this:
- [set checker](https://github.com/vmware-research/temporal-verifier/blob/36e811450c1ecc3841ee2cc56f016d16d66cad9b/bounded/src/set.rs#L598-L640)
- [sat checker](https://github.com/vmware-research/temporal-verifier/blob/36e811450c1ecc3841ee2cc56f016d16d66cad9b/bounded/src/sat.rs#L173-L215)
- [bdd checker](https://github.com/vmware-research/temporal-verifier/blob/36e811450c1ecc3841ee2cc56f016d16d66cad9b/bounded/src/bdd.rs#L202-L243)
- [verify/safety.rs via verify/module.rs](https://github.com/vmware-research/temporal-verifier/blob/36e811450c1ecc3841ee2cc56f016d16d66cad9b/verify/src/safety.rs#L40-L84)
- [inference/basics.rs](https://github.com/vmware-research/temporal-verifier/blob/36e811450c1ecc3841ee2cc56f016d16d66cad9b/inference/src/basics.rs#L134-L184)

My impression from glancing through these is that they are all pretty similar. I think the best use of flyvy internal data structures is in verify/safety.rs, so perhaps that is the one to keep. Right now that implementation is somewhat specific to invariant verification, and so would need to be generalized slightly. (Mostly just separating out the conversion to a transition system from the invariant stuff.)

**Comment by wilcoxjay** [comment]
I propose that we introduce a struct for "first order transition systems" that is similar to [verify::safety::InvariantAssertion](https://github.com/vmware-research/temporal-verifier/blob/36e811450c1ecc3841ee2cc56f016d16d66cad9b/verify/src/safety.rs#L13-L25) (but without the invariant stuff) and to [inference::basics::FOModule](https://github.com/vmware-research/temporal-verifier/blob/main/inference/src/basics.rs#L134-L143) (but without the weird algorithm-specific boolean configuration fields). And we have a `new` method for this struct that takes a flyvy `Module`.

**Comment by Alex-Fischman** [comment]
I'm currently working on this on branch [`transition-system-extraction`](https://github.com/vmware-research/temporal-verifier/tree/transition-system-extraction).
