### ISSUE TITLE
Z3 timeout during invariant inference

### ISSUE THREAD

**Issue by edenfrenkel** [vmware-research/temporal-verifier#68]
On the qalpha branch, Z3 consistently times out during the execution of
`cargo run -r -- infer examples/consensus_epr.fly --quantifier "* quorum 1" --quantifier "* node 3" --quantifier "* value 1" --max-clause-len 3 --max-clauses 1 --time --smt`
The printed error message is
`thread 'main' panicked at 'sat solver returned unknown: timeout', src/inference/basics.rs:129:45`

The same execution finishes without errors when using cvc5. (This takes a few minutes to run, though.)

An example of the resulting SMT file can be found at https://github.com/vmware-research/temporal-verifier/files/11517521/consensus_epr.txt .

**Comment by tchajed** [comment]
Closing, this example works with the new default timeout and we now also have `--timeout` to control it at the command line.
